### PR TITLE
fix: continuous rerendering by useCountDown hook

### LINKED ISSUE #109: `useCountDown` keeps rerendering after the deadline elapsed
In `DisputeTimeline` component, `useCountdown` hook keeps rerendering even if there is no time left. Probably a guard check should be in place to prevent unnecessary rerenders.

### PR DESCRIPTION
**Pull request by gratestas**
closes #109

### CODE REVIEW

File: src/hooks/useCountdown.js [hunk 1]
```diff
@@ -4,24 +4,26 @@ export default function useCountdown(deadline) {
...
     useEffect(() => {
+        if (timeLeft.totalInSeconds === 0) return;
+
         const interval = setInterval(() => {
             setTimeLeft(getTimeLeft(deadline));
         }, 1000);
 
         return () => clearInterval(interval);
-    }, [deadline]);
+    }, [deadline, timeLeft.totalInSeconds]);
```
Comment (0xferit) [inline src/hooks/useCountdown.js:14]: Is it really required to put `timeleft.totalInSeconds` to make it stop when it reaches to zero? I thought `if (...) return;` would do the job.

Comment (gratestas) [reply src/hooks/useCountdown.js:14]: @0xferit,  including `timeLeft.totalInSeconds` in the dependency array is necessary to reevaluate the effect whenever totalInSeconds reaches zero. 
`if (...) return;` is used to stop the interval from running when the countdown reaches zero. However, without including _totalInSeconds_ in the dependency array, the effect will not be re-run when the time is up. ( meaning that the interval will not be cleared, and the component will continue to update)

Comment (0xferit) [reply src/hooks/useCountdown.js:14]: Makes sense; thanks for explaining.
